export enum WalletEntryType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  RESERVE = 'RESERVE',
  RELEASE = 'RELEASE',
  SETTLE_DEBIT = 'SETTLE_DEBIT',
  SETTLE_CREDIT = 'SETTLE_CREDIT',
}