export enum OrderStatus {
  OPEN = 'OPEN',
  MATCH_PENDING = 'MATCH_PENDING',
  MATCHED = 'MATCHED',
  CANCELLED = 'CANCELLED',
  EXPIRED = 'EXPIRED',
  SETTLEMENT_FAILED = 'SETTLEMENT_FAILED',
}
